name: Get latest github activities workflow
on:
  schedule:
    - cron: "2 * * * *" # every 4 hours
  workflow_dispatch: # Run workflow manually (without waiting for the cron to be called), through the GitHub Actions Workflow page directly
  push: { branches: ["master", "main"] } # Run workflow when pushing on master/main
jobs:
  build:
    name: Update this repo's README with latest github activities
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: jamesgeorge007/github-activity-readme@master
        env:
          GITHUB_TOKEN: ${{ github.token }}
